# Moduiar Make - top level makefile
# PROJPATH = $(PWD)
# PROJNAME = $(notdir $(PROJPATH))
# EXT      = pdf
# TARGET := $(PROJNAME)$(EXT)
# TSTTGT := testapp$(EXT)

include $(shell find mk/ -name '*.mk')
